id: P64679D44
initial_creation_type: input
source_metadata:
  title: Khenpo Nüden Series
  language: bo
  description: 'Texts by the learned Khenpo Nüden Khyentse Lodrö (nus ldan mkhyen
    brtse''i blo gros, 19th–20th C.) of Kathok (kaḥ thog):'
  volume:
    97b69fc5390f45e78df44485db5d5029:
      title: 'Gateway to Learning: Four Great Logical Arguments of the Middle Way'
      parent: Buddhist Philosophy
created_at: '2022-03-01T00:26:14.808333'
last_modified_at: '2022-03-01T00:26:14.808336'
statistics:
  total_words: 3355
  total_non_words: 323
quality:
  non_words_ratio: 0.1
